version: '3.1'
services:
  mongo:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - creep
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: test
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
  metabase:
    image: metabase/metabase
    networks:
      - creep
    ports:
      - 3000:3000
networks:
  creep:
